#!/bin/sh

# Examples :
# ./gitsyncdir "https://github.com/Inist-CNRS/lodex-extended" "origin/rename-ws" "public/resources" /tmp/truc
# ./gitsyncdir "https://github.com/Inist-CNRS/lodex-extented" "v6.10.0" "public/webservices/netscity" $PWD/public

REPOSITORY=${1:?the first argument of the command should be the URL of a git repository.}
BRANCH=${2:-master}
SOURCE=$3
TARGET=${4:-/app/public}

LOCATION=$(dirname $TARGET)
DIRECTORY=$(basename $TARGET)

WORKDIR=/tmp/gitsyncdir

echo "Syncing $WORKDIR from $REPOSITORY with $BRANCH"

(test -d "$WORKDIR" && rm -rf "$WORKDIR")
mkdir -p "$WORKDIR/"
cd "$WORKDIR/"
git init
git remote add origin "$REPOSITORY"

git config core.sparseCheckout true
echo $SOURCE >> .git/info/sparse-checkout

git -c core.askpass=true fetch --all
git reset --hard "$BRANCH"
rm -rf "$WORKDIR/.git"

(test ! -d "$TARGET/" && mkdir -p "$TARGET/")

cp -Rf $WORKDIR/$SOURCE/* $TARGET/

rm -rf "$WORKDIR"
